
vscode:
  extensions:
    - 42Crunch.vscode-openapi

ports:
  - name: frontend
    port: 3000
    onOpen: open-browser
    visibility: public
  - name: backend
    port: 4567
    visibility: public
  - name: xray-daemon
    port: 2000
    visibility: public
  - port: 8008
    onOpen: ignore
  - port: 5432
    onOpen: ignore

image: marcopeg/gitpod-workspace-postgres:2.5.0